services:
  apache:
    build: ./www/php
    ports:
      - "80:80"
    volumes:
      - ./www/src:/usr/local/apache2/htdocs/
    depends_on:
      - php
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: poisson
      MYSQL_DATABASE: articles
      MYSQL_USER: poisson
      MYSQL_PASSWORD: poisson
    volumes:
      - ~/Users/bpoulain/projects/exo6/db_data:/var/lib/mysql
    platform: linux/x86_64
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: poisson
    ports:
      - "8080:80"
    depends_on:
      - mysql
  php:
    image: php:7.4-fpm
    volumes:
      - ./www/src:/usr/local/apache2/htdocs/
    ports:
      - "9000:9000"
